name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    uses: cto-af/workflows/.github/workflows/node-ci.yml@main
    with:
      nve: true
      script: ci
      versions: '[24]'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
